/**
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
 * 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence
 * whose values do not exceed four million, find the sum of the even-valued
 * terms.
 * */
public class EvenFibonacciNumbers {

	public static void main(String[] args) {
		EvenFibonacciNumbers fib = new EvenFibonacciNumbers();
		long sum = 0;
		for (int i = 0;; i++) {
			long fi = fib.fibo1(i);
			if (fi > 4000000)
				break;
			else if (fi % 2 == 0)
				sum += fi;
		}
		System.out.println("Total: " + sum); //Answer: 4613732
	}

	private long fibo1(long i) {
		if (i == 0 || i == 1)
			return i;
		else
			return fibo1(i - 1) + fibo1(i - 2);
	}

}